version: "3.9"
services:
  api:
    # container_name: backend
    # network_mode: host
    build: .
    volumes:
      - ./db:/db
    restart: always
    environment:
      - KUMA_SERVER=${KUMA_SERVER}
      - KUMA_USERNAME=${KUMA_USERNAME}
      - KUMA_PASSWORD=${KUMA_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
    ports:
      - "8000:8000"

volumes:
  uptime-kuma:
